version: '3.8'

services:
  ask-your-document:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./.env:/app/.env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
